version: '2'

services:
    db:
        extends:
            file: base.yml
            service: db   
        ports:
            - "5432" 
    web:
        extends:
            file: base.yml
            service: web
        build:
            args:
                - DJANGO_ENV=base
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
        volumes: 
            - ./web:/web
        depends_on: 
            - "db"     
        ports:
            - "8080:8080"

