# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('urlprecio', models.URLField()),
                ('cambios', models.ManyToManyField(blank=True, to='appmark.Cambio')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cambio',
            name='monedabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='appmark.Moneda'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='monedadestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='appmark.Moneda'),
        ),
    ]
