# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cambios', models.ManyToManyField(blank=True, to='appmark.Cambio')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('last', models.FloatField()),
                ('highest_bid', models.FloatField()),
                ('lowest_ask', models.FloatField()),
                ('base_volume', models.FloatField()),
                ('quote_volume', models.FloatField()),
                ('high_24hr', models.FloatField()),
                ('low_24hr', models.FloatField()),
                ('open_buy_orders', models.FloatField(default=0)),
                ('open_shell_orders', models.FloatField(default=0)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmark.Cambio')),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmark.Mercado')),
            ],
        ),
        migrations.AddField(
            model_name='cambio',
            name='monedabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='appmark.Moneda'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='monedadestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='appmark.Moneda'),
        ),
    ]
