# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercado',
            name='urlprecio',
        ),
    ]
