# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio',
            name='monedabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='appmark.Moneda'),
        ),
        migrations.AlterField(
            model_name='cambio',
            name='monedadestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='appmark.Moneda'),
        ),
    ]
