# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmark', '0002_auto_20160923_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='cambios',
            field=models.ManyToManyField(blank=True, to='appmark.Cambio'),
        ),
    ]
